# Generated by Django 3.2 on 2021-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211210_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(null=True, upload_to='album_img/'),
        ),
    ]
